# Generated by Django 5.2.11 on 2026-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Admin_name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('study', models.CharField(blank=True, max_length=100, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_No', models.IntegerField()),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
